-- CREATE DATABASE postgres_dev;
CREATE SEQUENCE revinfo_seq
    INCREMENT BY 50  -- Defina o tamanho de incremento desejado aqui
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START WITH 1;

CREATE TABLE REVINFO (
    REV INT PRIMARY KEY,
    REVTSTMP TIMESTAMP
);
