version: "3"
services:

  postgres_acao_social:
    container_name: postgres_acao_social
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=keycloack_postgres_db
    volumes:
      - ./db/backup_keycloak.sql:/docker-entrypoint-initdb.d/backup_keycloak.sql
    networks:
      network-social:
        ipv4_address: 172.16.19.2

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    restart: always
    environment:
      - KC_DB_URL=jdbc:postgresql://postgres_acao_social/keycloack_postgres_db
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_USERNAME=dev_user
      - KC_DB_PASSWORD=dev_password
    #      - KEYCLOAK_HTTP_PORT= 9090
    ports:
      - "9090:8080"
    command:
      - "start-dev"
    depends_on:
      - postgres_acao_social
    networks:
      network-social:
        ipv4_address: 172.16.19.3

  spring_boot_acao_social:
    container_name: spring_boot_acao_social
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - keycloak
    networks:
      network-social:
        ipv4_address: 172.16.19.4

networks:
  network-social:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.19.0/24