version: "3"
services:
  postgres_acao_social:
    container_name: postgres_acao_social
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - /var/lib/postgresql
    networks:
      net_postgres:
        ipv4_address: 172.16.19.2


  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    command:
      - "start-dev"

networks:
  keycloak-network:
    driver: bridge
  net_postgres:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.19.0/24