# http://localhost:9090/realms/realm-pantanal-dev/.well-known/openid-configuration
#db-name: social_action_postgres_db
db-name: postgres

server:
  port: '3001'
  host: http://localhost/

spring:
  flyway:
    enabled: false
  datasource:
    hikari:
      maxLifetime: '1800000'
      connectionTimeout: '500000'
      idleTimeout: '60000'
      maximumPoolSize: '10'
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${db-name}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/realm-pantanal-dev
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          realm-pantanal-dev:
            provider: realm-pantanal-dev
            client-name: client-id-backend-1
            client-id: client-id-backend-1
            client-secret: uXfLOkhKTekWg674dKs41GmU0a1vhHzG
            scope: openid,offline_access,profile
            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:
        provider:
          realm-pantanal-dev:
            issuer-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}
