server:
  port: '3001'
spring:
  datasource:
    hikari:
      maxLifetime: '1800000'
      connectionTimeout: '500000'
      idleTimeout: '60000'
      maximumPoolSize: '10'
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/dataDefinitionProduction

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/master
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          realm-pantanal-dev:
            provider: realm-pantanal-dev
            client-name: client-id-backend-1
            client-id: client-id-backend-1
            client-secret: dX3fgCppHye8Qhg7KCrPnitStXZVluiO
            scope: openid,offline_access,profile
            authorization-grant-type: authorization_code
        provider:
          poc-seila:
            issuer-uri: http://localhost:8084/realms/poc-seila
#jwt:
#  auth:
#    converter:
#      resource-id: client-id-pantanal
#      principle-attribute: preferred_username
