spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console-web
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
    baseline-on-migrate: false
