CREATE TABLE contract (
  version BIGINT NOT NULL,
  id UUID NOT NULL,
  company_id UUID NOT NULL,
  social_action_id UUID NOT NULL,
  ong_id UUID,
  process_id UUID,
  title VARCHAR(255),
  description VARCHAR(255),
  justification VARCHAR(255),
  status VARCHAR(255),
  evaluated_at TIMESTAMP,
  person_id UUID,
  created_by UUID,
  created_date TIMESTAMP,
  last_modified_by UUID,
  last_modified_date TIMESTAMP,
  deleted_date TIMESTAMP,
  deleted_by UUID,
  PRIMARY KEY (id),
  FOREIGN KEY (company_id) REFERENCES company (id),
  FOREIGN KEY (social_action_id) REFERENCES social_action (id),
  FOREIGN KEY (ong_id) REFERENCES ong (id),
  FOREIGN KEY (person_id) REFERENCES person (id)
);